language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.6"

install:
  - pip install -r requirements.txt

addons:
  apt:
   sources:
    - mysql-5.7-trusty
   packages:
    - mysql-server
    - mysql-client

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS PROJECT;'

script: ./test/test_app.py